### PR TITLE
Track the repository migration

### PR DESCRIPTION
**Pull request by shinnn**
```
git grep -l 'wooorm/vfile' | xargs sed -i '' 's/wooorm\/vfile/vfile\/vfile/g'
```

### CODE REVIEW

**Comment by shinnn** [comment]
Hmm. Though `.travis.yml` exists, Travis CI is not running.

**Comment by wooorm** [comment]
Great, thanks!
I’m trying to set up Travis but it’s hanging...

**Comment by shinnn** [comment]
I just committed again and now CI seems working!

**Comment by wooorm** [comment]
Thanks @shinnn!

**Comment by shinnn** [comment]
@wooorm No problem!

**Pull request merged**
