### PR TITLE
Add types

### PR DESCRIPTION
**Pull request by Rokt33r**
I think `type VFileCompatible = VFile | VFileOptions | VFileContents` should be in here. So after this pr is merged, I'll make another pr to discard it from `unified`.

### CODE REVIEW

**Comment by wooorm** [comment]
Nice! 👍

As the previous two type additions (`vfile-message`, `unified`) caused some of the ecosystem to break, I’d first like to figure out how to prevent that from happening before adding this.

**Comment by Rokt33r** [comment]
Absolutely!

**Comment by ChristianMurphy** [comment]
> maybe we need to change some other things in a major as well?

What do you have in mind @wooorm?

**Comment by Rokt33r** [comment]
> I do know that adding types to an API surfaces some weirdness, so if @Rokt33r finds things that are weird or hard to handle, we could change them now.

I don't' have any critical issues. But I sometimes thought it would be nice to have `.freeze()` method or `immutable-vfile` module.

**Comment by Rokt33r** [comment]
@wooorm I've updated `vfile-message`!

**Comment by wooorm** [comment]
This PR is good to go but `unist-util-stringify-position` needs to be updated with types first!

**Comment by wooorm** [comment]
Released! I’d like to add types to the rest of the vfile packages next, before we move on to unified and other things.

Here’s my proposed order (taking dependencies into account, for the needed major bumps):

zero deep:
* vfile-statistics
* vfile-location
* to-vfile
* vfile-sort
* vfile-is
* vfile-reporter-folder-json
* vfile-reporter-json

one deep:
* vfile-to-eslint (vfile-statistics)
* vfile-reporter (vfile-statistics)
* vfile-find-up (to-vfile)
* vfile-find-down (to-vfile)

two deep:
* vfile-reporter-pretty (vfile-to-eslint)

**Pull request merged**
