### PR TITLE
Upgraded dependencies

### PR DESCRIPTION
**Pull request by JuanM04**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

TypeScript was throwing a type error when using vfile. It turned out, npm downloaded `@types/unist` v2.0.3 instead of the latest v2.0.6. To prevent this, I've updated all the dependencies to it latest compatible version

### CODE REVIEW

**Review by ChristianMurphy — COMMENTED** [review]
Thanks for reaching out @JuanM04!
The `^` version range already allows and will usually install the latest verison of `@types/unist` (https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept)
If a project is getting stuck on an older version, it's usually due to a lockfile (package-lock.json or yarn.lock), and can be resolved by removing the lock file, or running `npm upgrade` or `yarn upgrade`

Unified intentionally uses wide version ranges to allow package managers to avoid version conflicts and deduplicate dependencies as much as possible.

**Comment by JuanM04** [comment]
Ok, but the package isn't compatible with this older version of `@types/unist`. Would you like me to update this PR to only change that version?

**Comment by JuanM04** [comment]
This is the commit that commit that breaks TS: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/df6c94b0ebb1446f1be2ccde75d8abb2340e205c (it was published in v2.0.6)

**Comment by ChristianMurphy** [comment]
@JuanM04 two points:
1. version 2.0.5 will be installed by default, and older version will only be used if you have it in your lockfile already
2. `@types/unist` 2.0.3 is compatible with the latest vfile (here tested with a script, with ts-node and latest TypeScript in strict mode) https://stackblitz.com/edit/node-t1e1wt?file=package.json

**Comment by JuanM04** [comment]
@ChristianMurphy I've tested your reproduction and you have `"skipLibCheck": true`. Remove that line and run `tsc --noEmit` and you'll see the error

Also, I've seen this error in the wild while using pnpm: it resolved to 2.0.3 not because of an old lockfile, but because there is a dependency that uses that version. I assume it chose the closest instead of the latest. Btw, it's not only your package that has this problem, other packages of the ecosystem (like unist-util-visit) also suffer this

**Comment by ChristianMurphy** [comment]
> because there is a dependency that uses that version

Which dependency? And how is it being introduced into the dependency tree?
If another package depends on an version of unist which isn't compatible with vfile or most of the unified ecosystem, that sounds like the root of the issue?

**Comment by JuanM04** [comment]
I don't know exactly. This is the lock file: https://github.com/JuanM04/portfolio/blob/main/pnpm-lock.yaml

> If another package depends on an version of unist which isn't compatible with vfile or most of the unified ecosystem, that sounds like the root of the issue?

Technically, no. What version NPM, Yarn or PNPM chooses for each package shouldn't matter as long as it's in the range declared in `package.json`. If the package says `^2.0.0`, I should be able to use it with `2.0.0`, `2.1.0`, `2.0.6`, and so on.

**Comment by JuanM04** [comment]
Thank you very much for the insight and detailed point of view. For now, I think I can fix it with [overrides](https://pnpm.io/package_json#pnpmoverrides) (as "refreshing the lockfile" doesn't quite work with pnpm, because it generates exactly the same one). I'll be following the progress of this issue and helping when posible.

**Pull request closed without merging**
