### PR TITLE
Closes #24: add posix mode option and document

### LINKED ISSUE #24: Add posix option to constructor
### Subject of the issue

Since we're talking about virtual files, it can often be essential to work with paths that are stable across systems. Currently, path calculations (e.g., `path.join`) are platform dependent. The vfile constructor should honor a posix option that switches a vfile instance from using path to [path.posix](https://nodejs.org/api/path.html#path_path_posix). That way, even on Windows, the path is always computed the same way, as a posix path (a path containing only forward slashes).

### Your environment

OS: Fedora (Linux)
Node: v8.9.4
npm: 5.6.0

### Steps to reproduce

Run the following on a Windows machine:

```js
const File = require('vfile')
const f = new File({ path: 'foo/bar/file.txt' })
f.dirname = 'foo/baz'
console.log(f.path)
```

### Expected behaviour

I want the script to output the following on Windows (if the proposed posix option is set):

```
foo/baz/file.txt
```

### Actual behaviour

On Windows, the script outputs:

```
foo\baz\file.txt
```

### Additional information

If the posix option is set, the path should also be normalized by changing all backslashes to forward slashes if the platform is win32.

### PR DESCRIPTION
**Pull request by mojavelinux**
This gets the ball rolling on #24. I still need to add tests to get back to 100% coverage.

### CODE REVIEW

**Comment by wooorm** [comment]
Looks like a good start! 👌

**Comment by mojavelinux** [comment]
:+1: I had a busy weekend. I'll have some updates soon.

**Comment by wooorm** [comment]
Sure, take you time!

**Comment by wooorm** [comment]
@mojavelinux Still interested in working on this?

**Comment by mojavelinux** [comment]
Yes. I've just had a lot of tasks to juggle recently. But I'll be getting back to this soon. Stay tuned.

**Comment by wooorm** [comment]
Sweet! Let me know if I can do anything!

**Comment by wooorm** [comment]
@mojavelinux What?

**Comment by wooorm** [comment]
@mojavelinux Ping!

**Comment by wooorm** [comment]
@mojavelinux Feel free to open a new issue, or ask me to reopen this if you’d like to work on it some more!

**Pull request closed without merging**
